### ISSUE TITLE
Make the minimap separatable and resizable

### ISSUE THREAD

**Issue by NahialMC** [Quzile/Project-Zomboid-EtherHack#10]
I love the minimap feature, but the hack window is too big and not resizable to be in constant display for it occupies a lot of the screen space. I suggest to make the minimap a separate window that we can drag over the existing game minimap or replace it.

**Comment by zazagamez42** [comment]
Already suggested in the Discord Server and taken into consideration :3

**Comment by Quzile** [comment]
Added in [release 2.3](https://github.com/Quzile/Project-Zomboid-EtherHack/releases/tag/v2.3)
