### ISSUE TITLE
Version 2.3 Player Edit Error

### ISSUE THREAD

**Issue by noweenose** [Quzile/Project-Zomboid-EtherHack#11]
Using this on a server, the player editor is not loading any UI and is prompting an error.

**Comment by Quzile** [comment]
Write more here in discord. Preferably a screenshot and error logs (You can find them in : `C:\Users\{username}\Zomboid\Logs`)

**Comment by Quzile** [comment]
Fixed in [release v2.4](https://github.com/Quzile/Project-Zomboid-EtherHack/releases/tag/v2.4)
