### ISSUE TITLE
Баг с Режимом мгновенного убийства

### ISSUE THREAD

**Issue by korevar** [Quzile/Project-Zomboid-EtherHack#12]
Ты можешь бить на неограниченной дистанции зомби и игроков,и у других игроков тоже появляется такая функция с неограниченной дистанцией поражения и мгновенным убийством

**Comment by Quzile** [comment]
Это не баг, так и задумано. При отключении, у оружия в инвентаре характеристики возвращаются к исходному значению. Чтобы у других не появлялось, не нужно передавать оружие с включенной функцией.
