### ISSUE TITLE
2 Патологии в чите

### ISSUE THREAD

**Issue by korevar** [Quzile/Project-Zomboid-EtherHack#2]
перейду к делу, я нашел баг с Ghost Mode  и с GetAdmin Access, при включении гост мода появляется неограниченое количество помещения в инвентаре ,а после выключение все встает на свои места,если можно то хотелось бы добавить неограниченое количество помещения в инвентаре а в гост моде убрать эту патологию,с админ меню проблема в том что меню не открывается,вот и моя подборка патологий в чите.

**Comment by korevar** [comment]
Надеюсь,автор это заметил это ДО меня ,и сейчасм решает данную проблему.

**Comment by Quzile** [comment]
> перейду к делу, я нашел баг с Ghost Mode и с GetAdmin Access, при включении гост мода появляется неограниченое количество помещения в инвентаре ,а после выключение все встает на свои места,если можно то хотелось бы добавить неограниченое количество помещения в инвентаре а в гост моде убрать эту патологию,с админ меню проблема в том что меню не открывается,вот и моя подборка патологий в чите.

Приветствую!
По поводу "Режима призрака", в новом релизе данная функция убрана, так как она полностью дублирует функционал "Невидимости" (Исходя из исходников игры). К тому же, так называемая "патология" с неограниченной грузоподъемностью  - функционал стандартных внутриигровых читов. Так что это не является ошибкой. 

Однако в [релизе 1.1](https://github.com/Quzile/Project-Zomboid-EtherHack/releases/tag/v1.1) добавлена отдельная функция "Неограниченной грузоподъемности".

Касательно панели администратора, действительно была проблема с открытием меню. Это обусловлено механикой античитов, поэтому на многих серверах, где они включены, функции данного характера работать не будут. Но теперь насильно открыть меню все-таки возможно через главное окно чита!
