### ISSUE TITLE
360 vision mode?

### ISSUE THREAD

**Issue by zee-lime** [Quzile/Project-Zomboid-EtherHack#3]
Is it possible to add a hack/cheat that would allow to see behind and all around you? Keeping the usual line-of-sight, but increasing the charater's field-of-view from 180 to 360 degrees.
Would be really nice to have one.

**Comment by Quzile** [comment]
Hello! Great idea, I'll consider implementing it in one of the next releases!)

**Comment by Quzile** [comment]
Added in [release 2.3](https://github.com/Quzile/Project-Zomboid-EtherHack/releases/tag/v2.3)
