### ISSUE TITLE
Presets/Configurations 

### ISSUE THREAD

**Issue by zazagamez42** [Quzile/Project-Zomboid-EtherHack#5]
It would be pretty convenient to have an "Options" tab and add a new feature that would save us all the time in the world CONFIGURATIONS /or PRESETS so we dont have to tick everything again on relaunch (THX SO MUCH 4 THE PROJECT ITS AN AMAZING WELL MADE HACK BY RUSSIAN TECH)

**Comment by Quzile** [comment]
Hello. Thanks for the idea, I'll try to implement it in one of the next versions)

**Comment by Quzile** [comment]
Added in [release v2.4](https://github.com/Quzile/Project-Zomboid-EtherHack/releases/tag/v2.4)
