### ISSUE TITLE
Problems occur with the cheat interface when using other languages

### ISSUE THREAD

**Issue by wangjb123456** [Quzile/Project-Zomboid-EtherHack#7]
If I use Chinese, the cheat screen will show UI plus information that shouldn't be there

**Comment by wangjb123456** [comment]
It should be that I am from China and I have tried other languages, and this bug occurs except English

**Comment by Quzile** [comment]
[FAQ - Translations](https://discord.com/channels/1132752206907592785/1133133490297258235/1133138219609899078)
[Discord](https://discord.gg/rQwCCpwDC)
